name: todo-app
services:
  backend:
    build: ./backend
    container_name: todo-app-backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network
  # frontend:
  #   build: ./frontend
  #   container_name: todo-app-frontend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend
  #   networks:
  #     - todo-network
  db:
    image: postgres:17-alpine
    container_name: todo-app-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d todo']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres-data:
